name: "Build & Deploy in Staging"

on:
  pull_request:
    branches:
      - 'feature**'
      - 'fix**'
    types:
      - closed  
    paths:
      - 'envs/stg/**'

jobs:
  staging-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/stg

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -out=tfplan
